title: Nitika Gahlawat 
logo: "/ID.JPG?raw=true" # your photo (or logo) here
description: > 
 Software Engineer (Frontend)
  <br><br>
  <a href="mailto:nitigahlawat03@gmail.com">nitigahlawat03@gmail.com </a>
  <br>
  <a href="https://www.linkedin.com/in/niti-kuhar//">LinkedIn Profile</a>
  <br>
  <a href="https://github.com/NitikaKuhar/">GitHub</a> 
theme: jekyll-theme-minimal
